# Banco de palabras de inglés. Crece cada semana según las clases.
# (palabra, español, emoji, tipo, ejemplo)
# group: id, name, week (semana en que se agregó / se usa en clase), note
VOCAB = [
 dict(id="garden", name="Unit 5: Garden animals", week="2026-09-28", note="Los 12 animales de la Unit 5 (Learning Well 3). Entran en el Written Quiz del 1 de octubre.",
  words=[("ant", "hormiga", "🐜", "noun", "The ant can run."),
         ("bat", "murciélago", "🦇", "noun", "The bat can fly at night."),
         ("bee", "abeja", "🐝", "noun", "The bees make honey."),
         ("beetle", "escarabajo", "🪲", "noun", "The beetle was in the tree."),
         ("butterfly", "mariposa", "🦋", "noun", "The butterfly can fly."),
         ("frog", "rana", "🐸", "noun", "The frog can jump."),
         ("hedgehog", "erizo", "🦔", "noun", "The hedgehog can run."),
         ("lizard", "lagartija", "🦎", "noun", "The lizard was on the rock."),
         ("owl", "búho", "🦉", "noun", "The owl has big eyes."),
         ("rabbit", "conejo", "🐇", "noun", "The rabbit can jump."),
         ("snail", "caracol", "🐌", "noun", "The snail doesn't have legs."),
         ("spider", "araña", "🕷️", "noun", "The spider has eight legs.")]),
 dict(id="garden2", name="More garden animals", week="2026-09-21", note="Otros animales del jardín (usados en la exposición).",
  words=[("ladybug", "mariquita", "🐞", "noun", "The ladybug is small and red."),
         ("worm", "gusano", "🪱", "noun", "The worm lives in the soil."),
         ("caterpillar", "oruga", "🐛", "noun", "The caterpillar eats leaves."),
         ("grasshopper", "saltamontes", "🦗", "noun", "The grasshopper can jump."),
         ("bird", "pájaro", "🐦", "noun", "The bird can sing.")]),
 dict(id="animalparts", name="Animal parts & abilities", week="2026-09-28", note="Para describir tu animal en la exposición.",
  words=[("wings", "alas", "🪽", "noun", "It has two wings."),
         ("legs", "patas", "🦵", "noun", "It has six legs."),
         ("antennae", "antenas", "#antennae", "noun", "It has two antennae."),
         ("shell", "caparazón / concha", "🐚", "noun", "The snail has a shell."),
         ("tail", "cola", "🐿️", "noun", "The squirrel has a big tail."),
         ("fly", "volar", "🕊️", "verb", "It can fly."),
         ("crawl", "arrastrarse / gatear", "🐍", "verb", "It can crawl."),
         ("jump", "saltar", "🦘", "verb", "It can jump."),
         ("sting", "picar", "🦂", "verb", "A bee can sting."),
         ("make honey", "hacer miel", "🍯", "verb", "Bees make honey.")]),
 dict(id="describe", name="Describing words", week="2026-09-28", note="Adjetivos para «It is…».",
  words=[("small", "pequeño", "🤏", "adj", "It is small."),
         ("big", "grande", "🐘", "adj", "It is big."),
         ("tiny", "diminuto", "🔬", "adj", "An ant is tiny."),
         ("colorful", "colorido", "🌈", "adj", "It is colorful."),
         ("slow", "lento", "🐢", "adj", "The snail is slow."),
         ("fast", "rápido", "⚡", "adj", "The grasshopper is fast."),
         ("long", "largo", "📏", "adj", "The worm is long."),
         ("green", "verde", "🟩", "adj", "The frog is green."),
         ("red", "rojo", "🟥", "adj", "The ladybug is red."),
         ("black", "negro", "⬛", "adj", "The ant is black.")]),
 dict(id="pronouns", name="Personal pronouns", week="base", note="Siempre repasar.",
  words=[("I", "yo", "🙋", "pronoun", "I am Thiago."),
         ("you", "tú / ustedes", "👉", "pronoun", "You are my friend."),
         ("he", "él", "👦", "pronoun", "He plays basketball."),
         ("she", "ella", "👧", "pronoun", "She reads books."),
         ("it", "eso (animal o cosa)", "🐶", "pronoun", "It is a dog."),
         ("we", "nosotros", "👨‍👩‍👧‍👦", "pronoun", "We are a family."),
         ("they", "ellos / ellas", "👫", "pronoun", "They are ants.")]),
 dict(id="verbs", name="Action verbs", week="base", note="Para present simple y present continuous.",
  words=[("play", "jugar", "⛹️", "verb", "I play basketball. / I am playing now."),
         ("run", "correr", "🏃", "verb", "He runs fast. / He is running."),
         ("jump", "saltar", "🤸", "verb", "Frogs jump. / The frog is jumping."),
         ("swim", "nadar", "🏊", "verb", "Fish swim. / She is swimming."),
         ("climb", "trepar", "🧗", "verb", "Monkeys climb trees."),
         ("walk", "caminar", "🚶", "verb", "I walk to the park."),
         ("eat", "comer", "🍽️", "verb", "Caterpillars eat leaves."),
         ("drink", "beber", "🥤", "verb", "I drink water."),
         ("read", "leer", "📖", "verb", "She reads every day."),
         ("write", "escribir", "✍️", "verb", "I write in my notebook."),
         ("sleep", "dormir", "😴", "verb", "The cat is sleeping."),
         ("sing", "cantar", "🎤", "verb", "Birds sing in the morning."),
         ("dance", "bailar", "💃", "verb", "They are dancing."),
         ("draw", "dibujar", "🖍️", "verb", "He draws animals."),
         ("listen", "escuchar", "👂", "verb", "Listen to the teacher."),
         ("watch", "mirar (TV)", "📺", "verb", "She watches TV."),
         ("ride", "montar", "🚲", "verb", "I ride my bike."),
         ("cook", "cocinar", "🍳", "verb", "Mom cooks rice.")]),
 dict(id="routines", name="Daily routines", week="base", note="Present simple + adverbs of frequency.",
  words=[("wake up", "despertarse", "⏰", "verb", "I wake up at six."),
         ("get dressed", "vestirse", "👕", "verb", "I get dressed."),
         ("brush my teeth", "cepillarme los dientes", "🪥", "verb", "I always brush my teeth."),
         ("take a shower", "bañarme", "🚿", "verb", "I take a shower at night."),
         ("have breakfast", "desayunar", "🥣", "verb", "I have breakfast at seven."),
         ("go to school", "ir a la escuela", "🏫", "verb", "I go to school by car."),
         ("do homework", "hacer la tarea", "📚", "verb", "I do my homework."),
         ("have dinner", "cenar", "🍝", "verb", "We have dinner together."),
         ("go to bed", "ir a dormir", "🛏️", "verb", "I go to bed at seven thirty.")]),
 dict(id="frequency", name="Adverbs of frequency", week="base", note="Van antes del verbo.",
  words=[("always", "siempre", "💯", "adverb", "I always brush my teeth."),
         ("usually", "normalmente", "🔁", "adverb", "I usually play basketball."),
         ("sometimes", "a veces", "🤷", "adverb", "I sometimes eat candy."),
         ("never", "nunca", "🚫", "adverb", "I never go to bed late.")]),
 dict(id="body", name="Human body (Natural Science)", week="2026-09-21", note="Natural Science 2Q, Partial 1.",
  words=[("skeleton", "esqueleto", "#skeleton", "noun", "The skeleton gives our body its shape."),
         ("bones", "huesos", "🦴", "noun", "Adults have 206 bones."),
         ("skull", "cráneo", "💀", "noun", "The skull protects the brain."),
         ("rib cage", "caja torácica", "#ribcage", "noun", "The rib cage protects the heart."),
         ("joints", "articulaciones", "🧎", "noun", "Knees are joints."),
         ("muscles", "músculos", "💪", "noun", "Muscles help us move."),
         ("heart", "corazón", "🫀", "noun", "The heart is a muscle."),
         ("brain", "cerebro", "🧠", "noun", "The brain is the boss."),
         ("spinal cord", "médula espinal", "#spine", "noun", "The spinal cord is like a highway."),
         ("nerves", "nervios", "#neuron", "noun", "Nerves send messages."),
         ("stomach", "estómago", "#stomach", "noun", "The stomach mixes the food."),
         ("lungs", "pulmones", "🫁", "noun", "We breathe with our lungs.")]),
]
