# Lengua y Literatura y Estudios Sociales
# Fuentes: comunicados semanales y canal EVALUACIONES (Teams), guías 1Q.
LEN = [
 dict(id="l-pronombres", s="len", q=2, st="actual", p=1, t="Pronombres personales",
  kid="Los pronombres reemplazan al nombre para no repetirlo. Entra en la Lección #1 del 29/09.",
  pts=["Yo, tú, él, ella", "Nosotros, nosotras", "Ustedes", "Ellos, ellas",
       "Thiago juega → Él juega", "Ana y mamá cocinan → Ellas cocinan"],
  quiz=[("«Thiago encesta.» ¿Qué pronombre reemplaza a Thiago?", ["Él", "Ella", "Nosotros"], 0, "Un niño → él."),
        ("«Mamá y Ana leen.» → ___ leen.", ["Ellas", "Ellos", "Yo"], 0, "Dos mujeres → ellas."),
        ("«Papá y yo jugamos.» → ___ jugamos.", ["Nosotros", "Ustedes", "Ellos"], 0, "Incluye a «yo» → nosotros."),
        ("¿Cuál es un pronombre personal?", ["tú", "mesa", "rápido"], 0, "Tú es pronombre."),
        ("«Los perros ladran.» → ___ ladran.", ["Ellos", "Él", "Nosotros"], 0, "Varios, masculino → ellos."),
        ("«Ana canta.» → ___ canta.", ["Ella", "Él", "Ellos"], 0, "Una niña → ella."),
        ("Cuando hablas de ti mismo usas…", ["yo", "él", "ustedes"], 0, "Yo = la persona que habla."),
        ("«Tú y tus amigos juegan.» → ___ juegan.", ["Ustedes", "Nosotros", "Yo"], 0, "Tú + otros → ustedes.")]),
 dict(id="l-verbo", s="len", q=2, st="actual", p=1, t="El verbo y el tiempo verbal",
  kid="El verbo es la palabra que dice la ACCIÓN. El tiempo verbal dice CUÁNDO pasa: ayer (pasado), hoy (presente) o mañana (futuro).",
  pts=["Verbo = acción: correr, saltar, comer, leer, cantar",
       "Pasado (ayer): Thiago jugó",
       "Presente (hoy, ahora): Thiago juega",
       "Futuro (mañana): Thiago jugará",
       "Truco: pon «ayer», «hoy» o «mañana» delante y mira cuál suena bien",
       "El verbo sin conjugar (infinitivo) termina en -ar, -er o -ir: cantar, comer, vivir"],
  table={"head": ["Pasado (ayer)", "Presente (hoy)", "Futuro (mañana)"], "rows": [["canté", "canto", "cantaré"], ["comí", "como", "comeré"], ["salté", "salto", "saltaré"], ["jugó", "juega", "jugará"]]},
  quiz=[("En «El perro corre en el parque», ¿cuál es el verbo?", ["corre", "perro", "parque"], 0, "Corre es la acción."),
        ("¿Cuál de estas palabras es un verbo?", ["saltar", "mesa", "azul"], 0, "Saltar es una acción."),
        ("«Ayer Thiago ___ básquet.»", ["jugó", "juega", "jugará"], 0, "Ayer → pasado: jugó."),
        ("«Mañana yo ___ a la playa.»", ["iré", "fui", "voy"], 0, "Mañana → futuro: iré."),
        ("«Hoy mi mamá ___ arroz.»", ["cocina", "cocinó", "cocinará"], 0, "Hoy → presente: cocina."),
        ("«Comeré» está en tiempo…", ["futuro", "pasado", "presente"], 0, "Comeré = lo haré después: futuro."),
        ("«Canté» está en tiempo…", ["pasado", "presente", "futuro"], 0, "Canté = ya pasó: pasado."),
        ("¿Qué verbo termina en -ir?", ["vivir", "cantar", "comer"], 0, "Vivir termina en -ir.")]),
 dict(id="l-catalogo", s="len", q=2, st="actual", p=1, t="El catálogo",
  kid="Un catálogo muestra productos para que la gente los conozca y los compre.",
  pts=["Imagen del producto", "Nombre", "Descripción corta (con adjetivos)", "Precio",
       "Está ordenado por secciones"],
  quiz=[("¿Para qué sirve un catálogo?", ["Para mostrar productos y venderlos", "Para contar un cuento", "Para escribir una carta"], 0, "Muestra productos."),
        ("¿Qué NO suele tener un catálogo?", ["Precio", "Imagen", "Nudo y desenlace"], 2, "Nudo y desenlace son partes de un cuento."),
        ("«Zapatillas rojas, ligeras y cómodas» es la…", ["descripción", "firma", "fecha"], 0, "Describe el producto con adjetivos."),
        ("En un catálogo los productos se ordenan en…", ["secciones", "estrofas", "párrafos de cuento"], 0, "Secciones: ropa, juguetes, etc.")]),
 dict(id="l-anuncio", s="len", q=2, st="actual", p=2, t="El anuncio publicitario",
  kid="Un anuncio quiere convencerte de comprar o usar algo.",
  pts=["Nombre del producto", "Imagen llamativa", "Eslogan: frase corta y fácil de recordar",
       "Adjetivos que convencen: rico, rápido, nuevo", "Dónde comprarlo o precio"],
  quiz=[("¿Qué es un eslogan?", ["Una frase corta que se recuerda", "El precio", "Un dibujo"], 0, "Ej.: «¡Salta más alto!»."),
        ("¿Para qué sirve un anuncio publicitario?", ["Para convencer", "Para narrar", "Para saludar"], 0, "Busca convencer."),
        ("¿Cuál es un buen eslogan para una pelota?", ["¡Rebota y gana!", "La pelota es un objeto.", "Había una vez una pelota."], 0, "Corto y llamativo."),
        ("¿Qué palabras ayudan a convencer en un anuncio?", ["rico, nuevo, rápido", "había una vez", "querido amigo"], 0, "Adjetivos que hacen ver bonito el producto."),
        ("¿Qué parte del anuncio llama la atención con colores?", ["La imagen", "La firma", "El nudo"], 0, "La imagen llamativa atrae a la gente.")]),
 dict(id="l-roles", s="len", q=2, st="actual", p=1, t="Juego de roles",
  kid="En un juego de roles actúas como un personaje: hablas y te mueves como él.",
  pts=["Cada uno tiene un papel (rol)", "Se respetan los turnos para hablar", "Se usa la voz y los gestos",
       "Se escucha a los compañeros"],
  quiz=[("En un juego de roles tú…", ["actúas como un personaje", "solo escribes", "no hablas"], 0, "Representas un personaje."),
        ("¿Qué es importante en un juego de roles?", ["Respetar los turnos", "Gritar", "Hablar todos a la vez"], 0, "Turnos y escuchar."),
        ("Si haces de vendedor, dices…", ["«¿Qué desea comprar?»", "«Había una vez…»", "«Querida abuela:»"], 0, "Hablas como el personaje."),
        ("¿Cómo se llama el papel que te toca actuar?", ["Rol", "Título", "Eslogan"], 0, "Tu papel es tu rol."),
        ("Mientras tu compañero habla, tú…", ["escuchas y esperas tu turno", "lo interrumpes", "te vas"], 0, "Escuchar es parte del juego.")]),
 dict(id="l-sustantivos", s="len", q=1, st="repaso", p=2, t="Clases de sustantivos",
  kid="El sustantivo nombra personas, animales, cosas, lugares o sentimientos.",
  pts=["Común: perro, ciudad · Propio (mayúscula): Thiago, Guayaquil",
       "Individual: árbol · Colectivo: bosque (muchos árboles)",
       "Concreto: se ve o toca (pelota) · Abstracto: no se toca (alegría, amor)",
       "Género: masculino / femenino · Número: singular / plural"],
  quiz=[("«Guayaquil» es un sustantivo…", ["propio", "común", "colectivo"], 0, "Nombre de un lugar: propio, con mayúscula."),
        ("«Jauría» (grupo de perros) es un sustantivo…", ["colectivo", "individual", "abstracto"], 0, "Nombra un grupo."),
        ("«Alegría» es un sustantivo…", ["abstracto", "concreto", "propio"], 0, "No se puede tocar."),
        ("«Pelota» es un sustantivo…", ["concreto", "abstracto", "propio"], 0, "Se puede tocar."),
        ("¿Cuál es colectivo?", ["enjambre", "abeja", "flor"], 0, "Enjambre = grupo de abejas."),
        ("El plural de «lápiz» es…", ["lápices", "lápizs", "lápiz"], 0, "z → ces.")]),
 dict(id="l-adjetivo", s="len", q=1, st="repaso", p=2, t="El adjetivo: género y número",
  kid="El adjetivo dice cómo es el sustantivo. Debe concordar: si el sustantivo es femenino y plural, el adjetivo también.",
  pts=["niño alto → niña alta (género)", "niño alto → niños altos (número)",
       "Adjetivos: grande, rápido, feliz, azul"],
  quiz=[("«La pelota es ___.»", ["rojo", "roja", "rojos"], 1, "Pelota es femenino singular → roja."),
        ("«Los perros ___.»", ["juguetón", "juguetones", "juguetona"], 1, "Masculino plural → juguetones."),
        ("¿Cuál es el adjetivo en «el gato negro duerme»?", ["gato", "negro", "duerme"], 1, "Negro dice cómo es el gato."),
        ("«Las flores son ___.»", ["bonitas", "bonito", "bonita"], 0, "Femenino plural → bonitas.")]),
 dict(id="l-articulo", s="len", q=1, st="repaso", p=3, t="El artículo",
  kid="El artículo va antes del sustantivo.",
  pts=["Definidos (algo conocido): el, la, los, las", "Indefinidos (algo no conocido): un, una, unos, unas"],
  quiz=[("___ niños juegan.", ["Los", "La", "El"], 0, "Masculino plural → los."),
        ("Compré ___ manzana.", ["una", "un", "unos"], 0, "Femenino singular indefinido → una."),
        ("¿Cuál es un artículo definido?", ["la", "una", "unos"], 0, "el, la, los, las son definidos."),
        ("___ mesas son nuevas.", ["Las", "Los", "El"], 0, "Femenino plural → las.")]),
 dict(id="l-sintactico", s="len", q=1, st="repaso", p=2, t="Análisis de la oración",
  kid="En una oración busca: artículo, sustantivo, adjetivo y verbo.",
  pts=["Ejemplo: «El perro grande corre.»",
       "El → artículo", "perro → sustantivo", "grande → adjetivo", "corre → verbo (acción)"],
  quiz=[("En «La niña feliz canta», ¿cuál es el verbo?", ["canta", "niña", "feliz"], 0, "El verbo es la acción."),
        ("En «Los gatos negros duermen», ¿cuál es el adjetivo?", ["negros", "gatos", "Los"], 0, "Dice cómo son."),
        ("En «Un pájaro vuela», «Un» es…", ["artículo", "verbo", "adjetivo"], 0, "Va antes del sustantivo."),
        ("En «El sol brilla», «sol» es…", ["sustantivo", "verbo", "artículo"], 0, "Nombra una cosa.")]),
 dict(id="l-puntos", s="len", q=1, st="repaso", p=3, t="Tipos de punto",
  kid="Los puntos separan ideas.",
  pts=["Punto y seguido: sigues escribiendo en la misma línea", "Punto y aparte: terminas el párrafo y empiezas otro",
       "Punto final: termina todo el texto"],
  quiz=[("El punto que termina todo el texto es…", ["punto final", "punto y seguido", "punto y aparte"], 0, "Punto final."),
        ("Para empezar un párrafo nuevo usas…", ["punto y aparte", "punto final", "punto y seguido"], 0, "Punto y aparte."),
        ("Si sigues escribiendo en la misma línea usas…", ["punto y seguido", "punto final"], 0, "Punto y seguido.")]),
 dict(id="l-ortografia", s="len", q=1, st="repaso", p=3, t="mp / mb, sílabas, sinónimos y antónimos",
  kid="Antes de p y b siempre se escribe m.",
  pts=["campo, hombre, tiempo, sombrero", "Monosílaba (1 sílaba): sol · Bisílaba (2): ca-sa",
       "Trisílaba (3): pe-lo-ta · Polisílaba (4 o más): ma-ri-po-sa",
       "Sinónimo: significa lo mismo (feliz = contento)", "Antónimo: significa lo contrario (alto ↔ bajo)"],
  quiz=[("¿Cuál está bien escrita?", ["campo", "canpo"], 0, "Antes de p va m."),
        ("¿Cuál está bien escrita?", ["hombre", "honbre"], 0, "Antes de b va m."),
        ("«Pelota» tiene…", ["3 sílabas", "2 sílabas", "4 sílabas"], 0, "pe-lo-ta."),
        ("Un sinónimo de «feliz» es…", ["contento", "triste", "bajo"], 0, "Significa lo mismo."),
        ("Un antónimo de «rápido» es…", ["lento", "veloz", "ligero"], 0, "Significa lo contrario.")]),
 dict(id="l-textos", s="len", q=1, st="repaso", p=3, t="Cuento fantástico, carta y onomatopeya",
  kid="Cada texto tiene sus partes.",
  pts=["Cuento: inicio, nudo (el problema) y desenlace (el final)",
       "Personajes principales y secundarios, y el lugar",
       "Carta: lugar y fecha, saludo, cuerpo, despedida, firma",
       "Onomatopeya: palabra que imita un sonido (guau, miau, ¡pum!, tic tac)"],
  quiz=[("La parte del cuento donde aparece el problema es…", ["el nudo", "el inicio", "la firma"], 0, "Nudo = problema."),
        ("¿Cuál es una onomatopeya?", ["¡Pum!", "Casa", "Rápido"], 0, "Imita un sonido."),
        ("En una carta, «Querida abuela:» es…", ["el saludo", "la despedida", "la firma"], 0, "Saludo."),
        ("¿Cómo termina un cuento?", ["Con el desenlace", "Con el nudo", "Con la fecha"], 0, "Desenlace = final.")]),
]

SOC = [
 dict(id="s-provincias", s="soc", q=2, st="actual", p=1, t="Las provincias del Ecuador",
  kid="Muchas provincias juntas forman nuestro país. Ecuador tiene 24 provincias.",
  pts=["Cada provincia tiene una capital",
       "Las provincias se dividen en cantones (Daule es un cantón de Guayas)",
       "Guayas → Guayaquil · Pichincha → Quito · Azuay → Cuenca",
       "Manabí → Portoviejo · Esmeraldas → Esmeraldas · El Oro → Machala",
       "Cotopaxi → Latacunga · Tungurahua → Ambato · Chimborazo → Riobamba",
       "Galápagos → Puerto Baquerizo Moreno",
       "Al inicio (1830) Ecuador tenía 3 departamentos: Quito, Guayaquil y Cuenca",
       "En 2007 se crearon 2 provincias nuevas: Santa Elena y Santo Domingo de los Tsáchilas",
       "Lección #1: miércoles 7 de octubre. Estudia el Trabajo individual y la Tarea #1"],
  quiz=[("¿Cuántas provincias tiene Ecuador?", ["24", "10", "4"], 0, "24 provincias."),
        ("La capital de Guayas es…", ["Guayaquil", "Quito", "Cuenca"], 0, "Guayaquil."),
        ("La capital de Pichincha (y del Ecuador) es…", ["Quito", "Ambato", "Machala"], 0, "Quito."),
        ("Las provincias se dividen en…", ["cantones", "países", "continentes"], 0, "Cantones, como Daule."),
        ("La capital de Azuay es…", ["Cuenca", "Loja", "Ibarra"], 0, "Cuenca."),
        ("La capital de Manabí es…", ["Portoviejo", "Manta", "Esmeraldas"], 0, "Portoviejo (Manta es una ciudad de Manabí, no su capital)."),
        ("Al inicio, Ecuador tenía 3 departamentos. ¿Cuáles?", ["Quito, Guayaquil y Cuenca", "Quito, Loja y Manta", "Guayas, Azuay y Napo"], 0, "Quito, Guayaquil y Cuenca."),
        ("¿Qué provincias nuevas se crearon en 2007?", ["Santa Elena y Santo Domingo de los Tsáchilas", "Guayas y Pichincha", "Napo y Pastaza"], 0, "Santa Elena y Santo Domingo de los Tsáchilas.")]),
 dict(id="s-nombres", s="soc", q=2, st="actual", p=1, t="¿Cómo se llaman las provincias?",
  kid="Muchas provincias tienen nombres de ríos, de volcanes o de personas importantes. Trabajo individual N°2 el miércoles 30 de septiembre.",
  pts=["Bolívar → en honor al Libertador Simón Bolívar",
       "Orellana → por Francisco de Orellana, que descubrió el río Amazonas",
       "Guayas → por el río Guayas y el cacique Guayas",
       "Los Ríos → por sus muchos ríos caudalosos",
       "Pastaza → por el río Pastaza (Amazonía)",
       "Esmeraldas → por las piedras preciosas verdes",
       "Chimborazo → por el volcán y pico más alto del Ecuador",
       "Pichincha e Imbabura → nombres de volcanes · Tungurahua = «garganta de fuego»",
       "En la Tarea #1 — nombres de montañas: Cotopaxi, Chimborazo, Pichincha, Imbabura, Tungurahua",
       "En la Tarea #1 — nombres de ríos: Esmeraldas, Pastaza, Napo, Cañar, Guayas, Carchi, Morona Santiago, Zamora Chinchipe",
       "Azuay → ligado a la historia y geografía cañari",
       "Apodos: Quito «Carita de Dios» · Ambato «Tierra de las Flores y las Frutas»",
       "Portoviejo «Ciudad de los Reales Tamarindos» · Machala «Capital Bananera del Mundo»"],
  quiz=[("¿Por qué Esmeraldas se llama así?", ["Por las piedras preciosas verdes", "Por un río", "Por un volcán"], 0, "Por las esmeraldas, piedras preciosas verdes."),
        ("La provincia Bolívar se llama así en honor a…", ["Simón Bolívar", "Francisco de Orellana", "un río"], 0, "Rinde homenaje al Libertador Simón Bolívar."),
        ("Chimborazo se llama así por…", ["el volcán más alto del Ecuador", "un héroe a caballo", "las piedras verdes"], 0, "El Chimborazo es el volcán y pico más alto del Ecuador."),
        ("Pastaza se llama así por…", ["un río de la Amazonía", "un volcán", "un presidente"], 0, "Por el río Pastaza."),
        ("¿Qué provincia tiene nombre de río?", ["Los Ríos", "Bolívar", "Chimborazo"], 0, "Los Ríos: por sus muchos ríos."),
        ("¿Qué ciudad es «Carita de Dios»?", ["Quito", "Machala", "Ambato"], 0, "Quito, Carita de Dios."),
        ("Machala es la «Capital…»", ["Bananera del Mundo", "de las Flores", "de los Tamarindos"], 0, "Machala, Capital Bananera del Mundo."),
        ("Ambato es la «Tierra de…»", ["las Flores y las Frutas", "los Volcanes", "la Nieve"], 0, "Ambato, Tierra de las Flores y las Frutas."),
        ("Portoviejo es la «Ciudad de los Reales…»", ["Tamarindos", "Bananos", "Volcanes"], 0, "Portoviejo, Ciudad de los Reales Tamarindos."),
        ("Orellana se llama así por…", ["Francisco de Orellana", "un volcán", "las flores"], 0, "El explorador que descubrió el río Amazonas."),
        ("¿Qué provincia tiene nombre de montaña (volcán)?", ["Cotopaxi", "Napo", "Guayas"], 0, "Cotopaxi es un volcán (montaña)."),
        ("¿Qué provincia tiene nombre de río?", ["Napo", "Tungurahua", "Imbabura"], 0, "Napo es un río."),
        ("Tungurahua, Imbabura y Pichincha tienen nombres de…", ["montañas (volcanes)", "ríos", "personas"], 0, "Son volcanes.")]),
 dict(id="s-regiones", s="soc", q=1, st="repaso", p=2, t="Las 4 regiones y su fauna",
  kid="Ecuador tiene 4 regiones: Costa, Sierra, Amazonía e Insular (Galápagos).",
  pts=["Costa: junto al océano Pacífico · iguana, cocodrilo, pelícano",
       "Sierra: montañas de los Andes · cóndor, oso andino, puma, vicuña",
       "Amazonía: selva, «pulmón del planeta» · jaguar, anaconda, delfín rosado",
       "Insular: Islas Galápagos · tortuga gigante, iguana marina, piquero de patas azules",
       "Límites: norte Colombia; sur y este Perú; oeste océano Pacífico"],
  quiz=[("El cóndor vive en la región…", ["Sierra", "Costa", "Insular"], 0, "Vive en los Andes."),
        ("La tortuga gigante vive en…", ["Galápagos", "la Amazonía", "la Sierra"], 0, "Región Insular."),
        ("El delfín rosado vive en…", ["la Amazonía", "la Costa", "la Sierra"], 0, "En los ríos amazónicos."),
        ("¿Qué país está al norte del Ecuador?", ["Colombia", "Perú", "Chile"], 0, "Colombia."),
        ("¿Qué océano está al oeste?", ["Pacífico", "Atlántico", "Índico"], 0, "Océano Pacífico."),
        ("Guayaquil está en la región…", ["Costa", "Sierra", "Amazonía"], 0, "Costa.")]),
 dict(id="s-tierra", s="soc", q=1, st="repaso", p=3, t="La Tierra y la red geográfica",
  kid="Para ubicar lugares en la Tierra usamos líneas imaginarias: paralelos y meridianos.",
  pts=["Paralelos: líneas horizontales → latitud",
       "Meridianos: líneas verticales → longitud",
       "La línea ecuatorial divide la Tierra en hemisferio norte y sur",
       "Ecuador está en América del Sur y lo cruza la línea ecuatorial"],
  quiz=[("Las líneas horizontales imaginarias son…", ["paralelos", "meridianos", "ríos"], 0, "Paralelos → latitud."),
        ("Los meridianos sirven para medir la…", ["longitud", "latitud", "temperatura"], 0, "Meridianos → longitud."),
        ("¿Qué divide a la Tierra en norte y sur?", ["La línea ecuatorial", "Un meridiano", "La cordillera"], 0, "La línea ecuatorial."),
        ("Ecuador está en…", ["América del Sur", "Europa", "África"], 0, "América del Sur.")]),
]

# Francés (4C FRANCAIS, Mme. Hellen Alarcón). Fuente: «4ÈME ACT CLASSE QUIM 2.pdf» (Teams, 21/09/2026), tema «Bonnes vacances».
FR = [
 dict(id="f-lieux", s="fr", q=2, st="actual", p=1, t="Les lieux de vacances (lugares)",
  kid="Tema del 2do quimestre: «Bonnes vacances». Aprende a decir a dónde vas de vacaciones.",
  pts=["la montagne = la montaña", "la plage = la playa", "la forêt = el bosque", "la campagne = el campo",
       "la ville = la ciudad", "l'île = la isla", "le lac = el lago", "le parc = el parque",
       "Je vais à la plage = Voy a la playa", "à + le = au: Je vais au lac"],
  listen=["Je vais à la plage.", "Je vais à la montagne.", "Moi, je vais à la campagne.", "Nous allons au camping au lac.", "Bonnes vacances !"],
  quiz=[("«La plage» es…", ["la playa", "la montaña", "el lago"], 0, "La plage = la playa."),
        ("«La montagne» es…", ["la montaña", "el bosque", "la ciudad"], 0, "La montagne = la montaña."),
        ("«La forêt» es…", ["el bosque", "la isla", "el parque"], 0, "La forêt = el bosque."),
        ("¿Cómo se dice «el lago»?", ["le lac", "la ville", "la plage"], 0, "Le lac = el lago."),
        ("¿Cómo se dice «la ciudad»?", ["la ville", "la campagne", "l'île"], 0, "La ville = la ciudad."),
        ("«L'île» es…", ["la isla", "el lago", "el campo"], 0, "L'île = la isla."),
        ("Completa: «Je vais ___ lac.»", ["au", "à la", "le"], 0, "à + le = au: Je vais au lac."),
        ("Escucha. ¿Qué lugar oyes?", ["la plage", "la forêt", "le parc"], 0, "Oíste: Je vais à la plage (la playa).", "Je vais à la plage.")]),
 dict(id="f-temps", s="fr", q=2, st="actual", p=1, t="Le temps (el clima)",
  kid="Para decir qué tiempo hace. Pregunta: «Quel temps fait-il ?» = ¿Qué tiempo hace?",
  pts=["Il fait beau = hace buen tiempo", "Il fait chaud = hace calor", "Il fait froid = hace frío", "Il fait mauvais = hace mal tiempo",
       "Il pleut = llueve", "Il neige = nieva", "Il y a du soleil = hay sol", "Il fait du vent = hace viento",
       "Il y a du brouillard = hay neblina", "Il y a de l'orage = hay tormenta"],
  listen=["Quel temps fait-il ?", "Il fait beau.", "Il fait chaud.", "Il fait froid.", "Il pleut.", "Il neige.", "Il y a du soleil.", "Il fait du vent."],
  quiz=[("«Il pleut» significa…", ["llueve", "nieva", "hace sol"], 0, "Il pleut = llueve."),
        ("«Il neige» significa…", ["nieva", "hace calor", "hace viento"], 0, "Il neige = nieva."),
        ("«Il fait chaud» significa…", ["hace calor", "hace frío", "hace mal tiempo"], 0, "Il fait chaud = hace calor."),
        ("¿Cómo se dice «hace frío»?", ["Il fait froid", "Il fait chaud", "Il fait beau"], 0, "Il fait froid = hace frío."),
        ("«Il y a du brouillard» significa…", ["hay neblina", "hay tormenta", "hay sol"], 0, "Brouillard = neblina."),
        ("«Il y a de l'orage» significa…", ["hay tormenta", "hay neblina", "hace viento"], 0, "Orage = tormenta."),
        ("«Il fait mauvais» significa…", ["hace mal tiempo", "hace buen tiempo", "hace calor"], 0, "Mauvais = malo."),
        ("Escucha. ¿Qué tiempo hace?", ["hace buen tiempo", "llueve", "nieva"], 0, "Oíste: Il fait beau (hace buen tiempo).", "Il fait beau !")]),
 dict(id="f-valise", s="fr", q=2, st="actual", p=2, t="Dans ma valise (mi maleta)",
  kid="Las cosas que pones en tu maleta para ir de vacaciones.",
  pts=["les lunettes de soleil = las gafas de sol", "la crème solaire = el protector solar", "l'appareil photo = la cámara de fotos",
       "les chaussures de marche = los zapatos para caminar", "la casquette = la gorra", "le maillot de bain = el traje de baño",
       "les tongs = las sandalias", "le short = el short", "l'anorak = la chaqueta para lluvia", "le t-shirt = la camiseta",
       "le pull = el suéter", "la gourde = la botella de agua"],
  listen=["Dans ma valise, je mets la crème solaire.", "Je mets la casquette.", "Je mets le maillot de bain.", "Je mets le pull."],
  quiz=[("«La casquette» es…", ["la gorra", "la camiseta", "la botella"], 0, "La casquette = la gorra."),
        ("«Le maillot de bain» es…", ["el traje de baño", "el suéter", "el short"], 0, "Maillot de bain = traje de baño."),
        ("¿Qué pones en la maleta para ir a la plage?", ["la crème solaire", "l'anorak", "le pull"], 0, "Para la playa: protector solar."),
        ("«La gourde» es…", ["la botella de agua", "la gorra", "la cámara"], 0, "La gourde = botella de agua."),
        ("«Les lunettes de soleil» son…", ["las gafas de sol", "los zapatos", "las sandalias"], 0, "Lunettes = gafas."),
        ("Hace frío en la montagne. ¿Qué pones?", ["le pull", "le maillot de bain", "les tongs"], 0, "Le pull = el suéter.")]),
 dict(id="f-activites", s="fr", q=2, st="actual", p=2, t="Les activités de vacances (verbos)",
  kid="Lo que haces en vacaciones.",
  pts=["nager = nadar", "lire = leer", "dormir = dormir", "jouer au ballon = jugar a la pelota",
       "me promener = pasear", "visiter une ville = visitar una ciudad"],
  listen=["Je nage.", "Je lis.", "Je dors.", "Je joue au ballon.", "Je me promène.", "Je visite une ville."],
  quiz=[("«Nager» es…", ["nadar", "leer", "dormir"], 0, "Nager = nadar."),
        ("«Lire» es…", ["leer", "nadar", "pasear"], 0, "Lire = leer."),
        ("«Jouer au ballon» es…", ["jugar a la pelota", "visitar una ciudad", "dormir"], 0, "Ballon = pelota."),
        ("«Me promener» es…", ["pasear", "nadar", "leer"], 0, "Me promener = pasear.")]),
 dict(id="f-jours", s="fr", q=2, st="actual", p=2, t="Les jours de la semaine",
  kid="Los días de la semana en francés. Se usan para decir qué tiempo hace cada día.",
  pts=["lundi = lunes", "mardi = martes", "mercredi = miércoles", "jeudi = jueves",
       "vendredi = viernes", "samedi = sábado", "dimanche = domingo"],
  listen=["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
  quiz=[("«Mercredi» es…", ["miércoles", "martes", "jueves"], 0, "Mercredi = miércoles."),
        ("¿Cómo se dice «sábado»?", ["samedi", "dimanche", "lundi"], 0, "Samedi = sábado."),
        ("«Jeudi» es…", ["jueves", "viernes", "lunes"], 0, "Jeudi = jueves."),
        ("¿Qué día va después de «lundi»?", ["mardi", "vendredi", "dimanche"], 0, "Lundi, mardi, mercredi…")]),
]

# Entornos Digitales (Miss Jennifer Alvarado). Fuente: publicación del 21/08/2026 en Teams (práctica de Word en casa).
DIG = [
 dict(id="d-word", s="dig", q=1, st="repaso", p=2, t="Word: letras, bordes y formas",
  kid="En el laboratorio aprendes Word. La profe pide practicar en casa: escribir una lectura corta y darle formato.",
  pts=["Escribe una lectura corta de 10 líneas", "N = Negrita · K = Cursiva · S = Subrayado",
       "Cambia el tamaño, el tipo y el color de la letra", "Mayúsculas (ABC) y minúsculas (abc)",
       "Pestaña Diseño → Bordes de página y Color de página", "Pestaña Insertar → Formas (y transformarlas en 3D)",
       "Copiar una imagen del navegador: clic derecho → Copiar imagen, y en Word: Pegar (Ctrl + V)"],
  quiz=[("¿Qué botón pone el texto en negrita?", ["N", "K", "S"], 0, "En Word en español: N = negrita, K = cursiva, S = subrayado."),
        ("¿Qué botón pone el texto en cursiva (letra inclinada)?", ["K", "N", "S"], 0, "K = cursiva."),
        ("¿En qué pestaña están las Formas?", ["Insertar", "Archivo", "Revisar"], 0, "Insertar → Formas."),
        ("Para poner un borde a toda la hoja usas…", ["Bordes de página", "Negrita", "Formas"], 0, "Bordes de página, en la pestaña Diseño."),
        ("Para copiar una imagen del navegador haces…", ["clic derecho → Copiar imagen", "doble clic en la imagen", "cerrar el navegador"], 0, "Clic derecho → Copiar imagen."),
        ("Para pegar la imagen en Word usas…", ["Ctrl + V", "Ctrl + Z", "Ctrl + P"], 0, "Ctrl + V = pegar."),
        ("Escribir con MAYÚSCULAS es…", ["letras grandes: ABC", "letras pequeñas: abc", "letras inclinadas"], 0, "Mayúsculas = letras grandes.")]),
]
