# Language Arts, Natural Science, Environmental Science
# Fuentes: canales de Miss Sheyla (Teams), rúbrica "GARDEN ANIMALS", Written Quiz 1/10, ppt "4TH NAT SCIE HUMAN BODY".
# Videos: YouTube, encontrados con búsqueda web el 27/09/2026 (se muestran como enlace + reproductor).
# quiz: (pregunta, opciones, índice correcto, explicación[, texto para escuchar])  -> con 5º elemento = pregunta de LISTENING
# st: "actual" (2Q, ahora en clase) · "base" (siempre repasar) · "repaso" (1Q)

ENG = [
 dict(id="e-garden", s="ing", q=2, st="actual", p=1, t="Unit 5: Garden animals",
  kid="Unit 5 (Learning Well 3): 12 animales del jardín. Entran en el Written Quiz del jueves 1 de octubre.",
  pts=["ant (hormiga) · bat (murciélago) · bee (abeja) · beetle (escarabajo)",
       "butterfly (mariposa) · frog (rana) · hedgehog (erizo) · lizard (lagartija)",
       "owl (búho) · rabbit (conejo) · snail (caracol) · spider (araña)",
       "can jump → frog, rabbit",
       "can fly → bat, bee, beetle, butterfly, owl",
       "doesn't have legs → snail",
       "A spider has eight legs · An ant has six legs",
       "This is a ___. · It is ___. · It has ___. · It can ___."],
  listen=["The frog can jump.", "The owl can fly at night.", "The snail doesn't have legs.", "The spider has eight legs.", "The bees make honey.", "The rabbit is in the garden."],
  videos=[("Animals in the garden (Wow English)", "EAmbAIIZ010"), ("Bugs & insects flashcards", "qXiaC1TjTXU")],
  quiz=[("Choose: «A butterfly ___ fly.»", ["can", "is", "has"], 0, "«can» = puede: It can fly."),
        ("An ant: «It ___ six legs.»", ["has", "is", "can"], 0, "«has» = tiene."),
        ("Which animal doesn't have legs?", ["snail", "spider", "ant"], 0, "The snail doesn't have legs."),
        ("A spider has ___ legs.", ["eight", "six", "four"], 0, "Spiders have eight legs (8 patas)."),
        ("Which animal can jump?", ["rabbit", "snail", "bat"], 0, "The rabbit (conejo) can jump."),
        ("Which animal can fly?", ["bat", "hedgehog", "lizard"], 0, "The bat (murciélago) can fly."),
        ("Which animal has big eyes and flies at night?", ["owl", "frog", "snail"], 0, "The owl (búho)."),
        ("Which animal makes honey?", ["bee", "snail", "lizard"], 0, "The bee makes honey (miel)."),
        ("«Hedgehog» en español es…", ["erizo", "conejo", "lagartija"], 0, "Hedgehog = erizo."),
        ("«Lizard» en español es…", ["lagartija", "murciélago", "escarabajo"], 0, "Lizard = lagartija."),
        ("Listen. Which sentence do you hear?", ["It can jump.", "It can fly.", "It can swim."], 1, "You heard: It can fly.", "It can fly."),
        ("Listen. Which animal is it?", ["rabbit", "spider", "snail"], 0, "It is a rabbit: it has long ears and it can jump.", "It is small. It has long ears. It can jump.")]),
 dict(id="e-spelling", s="ing", q=2, st="repaso", p=3, t="Spelling Bee (200 words)",
  kid="El miércoles 30 de septiembre te pedirán deletrear una palabra en inglés de la lista de 200 palabras. No tiene nota: es para practicar.",
  pts=["1. Escucha la palabra dos veces", "2. Dila tú en voz alta", "3. Deletrea letra por letra: b - e - a - c - h",
       "4. Al final repite la palabra: beach", "5. Practica 10 palabras por día con el juego «Deletrea»"],
  listen=["about", "balloon", "beautiful", "chocolate", "dictionary", "elephant", "family", "giraffe", "helicopter", "island", "kangaroo", "mountain", "ocean", "photograph", "science", "umbrella", "volcano", "yesterday"],
  quiz=[
        ("Listen. Which spelling is correct?", ['kalendar', 'calendar', 'calindar'], 1, "It is spelled: c-a-l-e-n-d-a-r.", "calendar"),
        ("Listen. Which spelling is correct?", ['garden', 'gerden', 'gardin'], 0, "It is spelled: g-a-r-d-e-n.", "garden"),
        ("Listen. Which spelling is correct?", ['newspaper', 'newcpaper', 'newspapper'], 0, "It is spelled: n-e-w-s-p-a-p-e-r.", "newspaper"),
        ("Listen. Which spelling is correct?", ['occasion', 'ocasion', 'okcasion'], 0, "It is spelled: o-c-c-a-s-i-o-n.", "occasion"),
        ("Listen. Which spelling is correct?", ['signature', 'signatur', 'cignature'], 0, "It is spelled: s-i-g-n-a-t-u-r-e.", "signature"),
        ("Listen. Which spelling is correct?", ['becaus', 'because', 'bekause'], 1, "It is spelled: b-e-c-a-u-s-e.", "because"),
        ("Listen. Which spelling is correct?", ['dictionary', 'dicctionary', 'diktionary'], 0, "It is spelled: d-i-c-t-i-o-n-a-r-y.", "dictionary"),
        ("Listen. Which spelling is correct?", ['realize', 'realiz', 'realizze'], 0, "It is spelled: r-e-a-l-i-z-e.", "realize"),
        ("Listen. Which spelling is correct?", ['scholarship', 'skholarship', 'scholarshep'], 0, "It is spelled: s-c-h-o-l-a-r-s-h-i-p.", "scholarship"),
        ("Listen. Which spelling is correct?", ['fotograph', 'photugraph', 'photograph'], 2, "It is spelled: p-h-o-t-o-g-r-a-p-h.", "photograph"),
        ("Listen. Which spelling is correct?", ['keyboard', 'kiyboard', 'keiboard'], 0, "It is spelled: k-e-y-b-o-a-r-d.", "keyboard"),
        ("Listen. Which spelling is correct?", ['problim', 'probblem', 'problem'], 2, "It is spelled: p-r-o-b-l-e-m.", "problem"),
        ("Listen. Which spelling is correct?", ['patienke', 'patienci', 'patience'], 2, "It is spelled: p-a-t-i-e-n-c-e.", "patience"),
        ("Listen. Which spelling is correct?", ['musiccian', 'mosician', 'musician'], 2, "It is spelled: m-u-s-i-c-i-a-n.", "musician"),
        ("Listen. Which spelling is correct?", ['quicckly', 'quickly', 'quickkly'], 1, "It is spelled: q-u-i-c-k-l-y.", "quickly"),
        ("Listen. Which spelling is correct?", ['leadership', 'leaddership', 'leaderchip'], 0, "It is spelled: l-e-a-d-e-r-s-h-i-p.", "leadership"),
        ("Listen. Which spelling is correct?", ['effective', 'efective', 'effictive'], 0, "It is spelled: e-f-f-e-c-t-i-v-e.", "effective"),
        ("Listen. Which spelling is correct?", ['ebout', 'about', 'abot'], 1, "It is spelled: a-b-o-u-t.", "about"),
        ("Listen. Which spelling is correct?", ['resourke', 'resource', 'resourci'], 1, "It is spelled: r-e-s-o-u-r-c-e.", "resource"),
        ("Listen. Which spelling is correct?", ['balanc', 'balanke', 'balance'], 2, "It is spelled: b-a-l-a-n-c-e.", "balance"),
        ("Listen. Which spelling is correct?", ['believe', 'bellieve', 'believ'], 0, "It is spelled: b-e-l-i-e-v-e.", "believe"),
        ("Listen. Which spelling is correct?", ['family', 'fammily', 'famili'], 0, "It is spelled: f-a-m-i-l-y.", "family"),
        ("Listen. Which spelling is correct?", ['beautiful', 'biautiful', 'beauteful'], 0, "It is spelled: b-e-a-u-t-i-f-u-l.", "beautiful"),
        ("Listen. Which spelling is correct?", ['managger', 'maneger', 'manager'], 2, "It is spelled: m-a-n-a-g-e-r.", "manager"),
        ("Listen. Which spelling is correct?", ['absennt', 'abcent', 'absent'], 2, "It is spelled: a-b-s-e-n-t.", "absent"),
        ("Listen. Which spelling is correct?", ['vicctory', 'viktory', 'victory'], 2, "It is spelled: v-i-c-t-o-r-y.", "victory"),
        ("Listen. Which spelling is correct?", ['teecher', 'teacher', 'teakher'], 1, "It is spelled: t-e-a-c-h-e-r.", "teacher"),
        ("Listen. Which spelling is correct?", ['gallery', 'gellery', 'galliry'], 0, "It is spelled: g-a-l-l-e-r-y.", "gallery"),
        ("Listen. Which spelling is correct?", ['depennd', 'depind', 'depend'], 2, "It is spelled: d-e-p-e-n-d.", "depend"),
        ("Listen. Which spelling is correct?", ['innsect', 'insect', 'insict'], 1, "It is spelled: i-n-s-e-c-t.", "insect"),
        ("Listen. Which spelling is correct?", ['emution', 'emottion', 'emotion'], 2, "It is spelled: e-m-o-t-i-o-n.", "emotion"),
        ("Listen. Which spelling is correct?", ['helicupter', 'helicopter', 'helikopter'], 1, "It is spelled: h-e-l-i-c-o-p-t-e-r.", "helicopter"),
        ("Listen. Which spelling is correct?", ['holliday', 'holiday', 'holidday'], 1, "It is spelled: h-o-l-i-d-a-y.", "holiday"),
        ("Listen. Which spelling is correct?", ['importannce', 'importance', 'importence'], 1, "It is spelled: i-m-p-o-r-t-a-n-c-e.", "importance"),
        ("Listen. Which spelling is correct?", ['xylophone', 'xyylophone', 'xylophune'], 0, "It is spelled: x-y-l-o-p-h-o-n-e.", "xylophone"),
        ("Listen. Which spelling is correct?", ['seccurity', 'securrity', 'security'], 2, "It is spelled: s-e-c-u-r-i-t-y.", "security"),
        ("Listen. Which spelling is correct?", ['bakkpack', 'backpack', 'backpeck'], 1, "It is spelled: b-a-c-k-p-a-c-k.", "backpack"),
        ("Listen. Which spelling is correct?", ['happiness', 'happiniss', 'happinecs'], 0, "It is spelled: h-a-p-p-i-n-e-s-s.", "happiness"),
        ("Listen. Which spelling is correct?", ['banana', 'banena', 'bananna'], 0, "It is spelled: b-a-n-a-n-a.", "banana"),
        ("Listen. Which spelling is correct?", ['welcomme', 'welcom', 'welcome'], 2, "It is spelled: w-e-l-c-o-m-e.", "welcome")]),
 dict(id="e-waswere", s="ing", q=2, st="actual", p=1, t="Was / Were",
  kid="Was y were son el verbo to be en pasado: lo que ERA o ESTABA antes. Entra en el Written Quiz del jueves 1 de octubre.",
  pts=["I / he / she / it → was", "you / we / they → were", "Negativo: wasn't / weren't",
       "Lugares: in the tree · on the rock · on the flower · in the water · on the grass · on a leaf",
       "Pregunta: Was it…? / Were they…?", "Truco: si son varios (plural) → were"],
  table={"head": ["Presente", "Pasado"], "rows": [["I am", "I was"], ["You are", "You were"], ["He / She / It is", "He / She / It was"], ["We are", "We were"], ["They are", "They were"]]},
  listen=["I was at home yesterday.", "The bee was on the flower.", "They were in the garden.", "We were happy.", "Was it big? No, it wasn't."],
  videos=[("Was – Were for kids (Grammar)", "-bfPNv1vYXo"), ("I Was, You Were – song (Rockin' English)", "KAsacxmPh1Q")],
  quiz=[("I ___ at home yesterday.", ["was", "were"], 0, "I → was."),
        ("They ___ happy.", ["was", "were"], 1, "They → were."),
        ("She ___ in the garden.", ["was", "were"], 0, "She → was."),
        ("We ___ at school.", ["was", "were"], 1, "We → were."),
        ("The ants ___ small.", ["was", "were"], 1, "The ants = they (plural) → were."),
        ("___ you tired?", ["Was", "Were"], 1, "You → were."),
        ("The bee ___ on the flower.", ["was", "were"], 0, "The bee = it → was."),
        ("Listen. Which word do you hear?", ["was", "were"], 1, "You heard «were»: The spiders were big.", "The spiders were big."),
        ("Listen. Which word do you hear?", ["was", "were"], 0, "You heard «was»: The snail was slow.", "The snail was slow."),
        ("The snails ___ on the tree. (No estaban)", ["weren't", "wasn't"], 0, "snails = they → weren't."),
        ("The owl ___ in the water. (No estaba)", ["wasn't", "weren't"], 0, "owl = it → wasn't."),
        ("The lizard ___ on the rock.", ["was", "were"], 0, "lizard = it → was."),
        ("The frogs ___ in the water.", ["were", "was"], 0, "frogs = they → were."),
        ("The children ___ in the garden.", ["were", "was"], 0, "children = they (plural) → were."),
        ("The rabbit ___ on the grass. (No estaba)", ["wasn't", "weren't"], 0, "rabbit = it → wasn't.")]),
 dict(id="e-instrucciones", s="ing", q=2, st="actual", p=1, t="Exam words: entender las instrucciones",
  kid="En el examen escrito primero hay que entender QUÉ te piden. Subraya la palabra de la instrucción ANTES de responder.",
  pts=["Circle = encierra en un círculo", "Underline = subraya", "Match = une con líneas",
       "Complete / Fill in the blanks = completa los espacios", "Choose = elige", "Write = escribe", "Read = lee",
       "Color = pinta · Draw = dibuja", "True or False = verdadero o falso", "Answer the questions = responde las preguntas"],
  listen=["Circle the correct answer.", "Underline the verb.", "Match the words with the pictures.", "Fill in the blanks.", "Read and answer the questions."],
  videos=[("Classroom instructions for kids", "Qux7tB6uhcQ")],
  quiz=[("«Underline» means…", ["Encierra", "Subraya", "Dibuja"], 1, "Underline = subraya (línea debajo)."),
        ("«Match» means…", ["Une con líneas", "Pinta", "Escribe"], 0, "Match = une."),
        ("«Circle the correct answer» means…", ["Encierra la respuesta correcta", "Escribe la respuesta", "Dibuja la respuesta"], 0, "Circle = encierra en un círculo."),
        ("«Fill in the blanks» means…", ["Completa los espacios", "Borra", "Lee en voz alta"], 0, "Blanks = espacios vacíos."),
        ("«True or False» means…", ["Verdadero o falso", "Uno o dos", "Grande o pequeño"], 0, "True = verdadero, False = falso."),
        ("Listen. What do you have to do?", ["Subrayar", "Encerrar", "Dibujar"], 0, "You heard «Underline» = subrayar.", "Underline the verbs."),
        ("Listen. What do you have to do?", ["Unir con líneas", "Pintar", "Escribir"], 0, "You heard «Match» = unir.", "Match the animals with their names.")]),
 dict(id="e-pronouns", s="ing", q=2, st="base", p=1, t="Personal pronouns (I, you, he, she, it, we, they)",
  kid="Los pronombres personales reemplazan el nombre de una persona, animal o cosa. En inglés siempre van antes del verbo.",
  pts=["I = yo", "you = tú / ustedes", "he = él (un niño, un hombre)", "she = ella (una niña, una mujer)",
       "it = eso (un animal o una cosa)", "we = nosotros", "they = ellos / ellas (varios)",
       "Thiago plays → He plays · The bee flies → It flies"],
  table={"head": ["Pronoun", "Español", "Ejemplo"], "rows": [["I 🙋", "yo", "I am Thiago."], ["You 👉", "tú", "You are my friend."], ["He 👦", "él", "He plays basketball."], ["She 👧", "ella", "She reads."], ["It 🐶", "eso (animal/cosa)", "It is a dog."], ["We 👨‍👩‍👧", "nosotros", "We are a team."], ["They 👫", "ellos / ellas", "They run."]]},
  listen=["I am Thiago.", "He is my brother.", "She is my sister.", "It is a butterfly.", "We are friends.", "They are ants."],
  videos=[("Subject pronouns for kids (I, you, we, they, he, she, it)", "Ke7j1jFLxbc"), ("The Personal Pronoun Song", "zApm7GfRtNw")],
  quiz=[("«Thiago» → ___", ["He", "She", "It"], 0, "Un niño → he."),
        ("«Mom» → ___", ["She", "He", "They"], 0, "Una mujer → she."),
        ("«The dog» → ___", ["It", "He", "We"], 0, "Un animal → it."),
        ("«Ana and Mom» → ___", ["They", "We", "She"], 0, "Varias personas → they."),
        ("«Dad and I» → ___", ["We", "They", "You"], 0, "Incluye «I» → we."),
        ("___ am 8 years old.", ["I", "He", "They"], 0, "I am."),
        ("«The ants» → ___", ["They", "It", "He"], 0, "Varios animales → they."),
        ("Listen. Which pronoun do you hear?", ["she", "he", "we"], 0, "You heard: She is my teacher.", "She is my teacher."),
        ("Listen. Which pronoun do you hear?", ["they", "we", "it"], 0, "You heard: They are in the garden.", "They are in the garden.")]),
 dict(id="e-simple", s="ing", q=2, st="base", p=1, t="Present simple (lo que haces siempre)",
  kid="El presente simple es para rutinas y cosas que siempre pasan. Con he, she, it el verbo lleva -s.",
  pts=["I / you / we / they + verbo: I play basketball.", "He / she / it + verbo + s: He plays basketball.",
       "-es con verbos que terminan en o, sh, ch, x: go → goes, watch → watches, brush → brushes",
       "consonante + y → ies: fly → flies, study → studies",
       "Negativo: I don't play · He doesn't play (sin -s)", "Pregunta: Do you play? · Does he play?",
       "Palabras pista: every day, always, usually, sometimes, never, on Saturdays"],
  table={"head": ["", "Afirmativo", "Negativo"], "rows": [["I", "I play", "I don't play"], ["You", "You play", "You don't play"], ["He / She / It", "He plays", "He doesn't play"], ["We", "We play", "We don't play"], ["They", "They play", "They don't play"]]},
  listen=["I play basketball on Saturdays.", "She reads every day.", "A bee flies to the flowers.", "He doesn't like soup.", "Do you brush your teeth every morning?"],
  videos=[("Present simple for kids – daily routines", "1vc3jqgLEKU"), ("Present simple tense for kids", "EzndAIX9x30")],
  quiz=[("He ___ basketball every Saturday.", ["play", "plays", "playing"], 1, "He → plays (con -s)."),
        ("I ___ my teeth every morning.", ["brush", "brushes", "brushing"], 0, "I → brush (sin -s)."),
        ("A bee ___ to the flowers.", ["fly", "flies", "flys"], 1, "fly → flies (y → ies)."),
        ("She ___ TV at night.", ["watch", "watches", "watchs"], 1, "watch → watches (-es)."),
        ("They ___ like spiders.", ["don't", "doesn't"], 0, "They → don't."),
        ("___ he go to school by car?", ["Do", "Does"], 1, "He → does."),
        ("My dad ___ to work every day.", ["go", "goes", "going"], 1, "go → goes."),
        ("Listen. Which sentence do you hear?", ["She reads every day.", "She is reading now.", "She read yesterday."], 0, "Present simple: every day.", "She reads every day.")]),
 dict(id="e-continuous", s="ing", q=2, st="base", p=1, t="Present continuous (lo que pasa AHORA)",
  kid="El presente continuo es para lo que está pasando en este momento: am / is / are + verbo con -ing.",
  pts=["I am + verbo-ing: I am reading.", "He / she / it is + verbo-ing: She is running.",
       "You / we / they are + verbo-ing: They are playing.",
       "Verbos que terminan en e: quita la e → make → making, dance → dancing",
       "Consonante-vocal-consonante: dobla → run → running, swim → swimming, sit → sitting",
       "Negativo: I'm not playing · He isn't playing · They aren't playing",
       "Palabras pista: now, right now, at the moment, Look!, Listen!"],
  table={"head": ["", "Ahora mismo"], "rows": [["I", "I am jumping"], ["You", "You are jumping"], ["He / She / It", "It is jumping"], ["We", "We are jumping"], ["They", "They are jumping"]]},
  listen=["Look! The butterfly is flying.", "I am reading a book now.", "They are playing basketball.", "She is running in the park.", "We are swimming right now."],
  videos=[("Present continuous for kids", "0-tku3eRs4I"), ("What are you doing? (present continuous)", "lPY9sYK5S5A"), ("Present continuous explicado en español (Mr. Pea)", "lGkxRXamy7Y")],
  quiz=[("Look! The butterfly ___ flying.", ["is", "are", "am"], 0, "The butterfly = it → is."),
        ("I ___ reading now.", ["am", "is", "are"], 0, "I → am."),
        ("They ___ playing basketball.", ["are", "is", "am"], 0, "They → are."),
        ("run → ___", ["running", "runing", "runeing"], 0, "Se dobla la n: running."),
        ("make → ___", ["making", "makeing", "makking"], 0, "Quita la e: making."),
        ("swim → ___", ["swimming", "swiming", "swimeing"], 0, "Se dobla la m: swimming."),
        ("She ___ sleeping. (negativo)", ["isn't", "aren't", "don't"], 0, "She → isn't."),
        ("Listen. What is he doing?", ["He is jumping.", "He is sleeping.", "He is eating."], 0, "You heard: He is jumping.", "Look! He is jumping.")]),
 dict(id="e-progressive", s="ing", q=2, st="base", p=2, t="Present simple vs present continuous",
  kid="¿Siempre o ahora? Siempre / todos los días → present simple. Ahora mismo → present continuous.",
  pts=["Every day: I play basketball. (rutina)", "Now: I am playing basketball. (en este momento)",
       "every day, always, usually, on Mondays → present simple", "now, right now, Look!, at the moment → present continuous",
       "Adverbs of manner: quick → quickly, slow → slowly, careful → carefully"],
  table={"head": ["Siempre (simple)", "Ahora (continuous)"], "rows": [["I play every day.", "I am playing now."], ["She reads at night.", "She is reading now."], ["It flies.", "It is flying."]]},
  listen=["I play basketball every Saturday.", "Look! I am playing basketball now.", "She reads every night.", "She is reading right now."],
  videos=[("Present simple and present continuous for kids", "umRi1-xdAHU")],
  quiz=[("Look! He ___ now.", ["is running", "runs"], 0, "Now → present continuous."),
        ("I ___ basketball every Saturday.", ["am playing", "play"], 1, "Every Saturday = rutina → simple."),
        ("She ___ a book right now.", ["is reading", "reads"], 0, "Right now → is reading."),
        ("Ants ___ in groups. (always)", ["live", "are living"], 0, "Siempre → present simple."),
        ("slow → ___", ["slowly", "slowy", "slower"], 0, "Adverbio de modo: slow + ly."),
        ("Listen. Is it a routine or now?", ["Now", "Routine"], 0, "«right now» → present continuous.", "The frog is jumping right now.")]),
 dict(id="e-tobe", s="ing", q=1, st="base", p=2, t="Verb to be (am / is / are)",
  kid="To be es ser o estar. Cambia según la persona.",
  pts=["I am", "He / She / It is", "You / We / They are", "Negativo: I'm not, isn't, aren't"],
  table={"head": ["", "to be", "Negativo"], "rows": [["I", "am", "I'm not"], ["He / She / It", "is", "isn't"], ["You / We / They", "are", "aren't"]]},
  listen=["I am happy.", "It is a snail.", "We are in fourth grade.", "They aren't big."],
  videos=[("Am – Is – Are | Verb to be for kids", "Tq1TxNgs4Ls"), ("Verb to be for kids", "cEzSLzzKkf0")],
  quiz=[("I ___ Thiago.", ["am", "is", "are"], 0, "I → am."),
        ("She ___ my teacher.", ["am", "is", "are"], 1, "She → is."),
        ("They ___ friends.", ["am", "is", "are"], 2, "They → are."),
        ("It ___ a dog.", ["am", "is", "are"], 1, "It → is."),
        ("We ___ in 4th grade.", ["am", "is", "are"], 2, "We → are.")]),
 dict(id="e-routines", s="ing", q=1, st="repaso", p=2, t="Routines + adverbs of frequency",
  kid="Los adverbios de frecuencia dicen cada cuánto haces algo.",
  pts=["always = siempre (100%)", "usually = normalmente", "sometimes = a veces", "never = nunca (0%)",
       "Van antes del verbo: I always brush my teeth", "Van después de is/am/are: He is never late"],
  listen=["I always brush my teeth.", "I usually have breakfast at seven.", "I sometimes play video games.", "I never go to bed late."],
  videos=[("Adverbs of frequency for kids", "y1l7OTgbC7Y"), ("Adverbios de frecuencia explicado en español (Mr. Pea)", "WC2tzXPIWMs")],
  quiz=[("«Never» means…", ["siempre", "nunca", "a veces"], 1, "Never = 0%."),
        ("Choose: «I ___ eat breakfast.» (100%)", ["always", "never", "sometimes"], 0, "Always = siempre."),
        ("Which is correct?", ["I play always basketball.", "I always play basketball.", "Always I basketball play."], 1, "El adverbio va antes del verbo."),
        ("«Sometimes» means…", ["a veces", "nunca", "siempre"], 0, "Sometimes = a veces.")]),
 dict(id="e-someany", s="ing", q=1, st="repaso", p=3, t="Food: some / any",
  kid="Some en oraciones afirmativas. Any en negativas y preguntas.",
  pts=["There is some milk.", "There isn't any milk.", "Is there any milk?"],
  listen=["There are some apples.", "There isn't any juice.", "Are there any eggs?"],
  videos=[("Some – Any for kids", "H57QBF9mR-g")],
  quiz=[("There are ___ apples.", ["some", "any"], 0, "Afirmativa → some."),
        ("There aren't ___ eggs.", ["some", "any"], 1, "Negativa → any."),
        ("Is there ___ juice?", ["some", "any"], 1, "Pregunta → any."),
        ("I have ___ bread.", ["some", "any"], 0, "Afirmativa → some.")]),
 dict(id="e-comparatives", s="ing", q=1, st="repaso", p=2, t="Animals: comparatives",
  kid="Para comparar dos cosas: adjetivo corto + er + than, o more + adjetivo largo + than.",
  pts=["tall → taller than", "big → bigger than (se dobla la g)", "happy → happier than (y → i)", "beautiful → more beautiful than"],
  listen=["An elephant is bigger than a mouse.", "A giraffe is taller than a dog.", "A cheetah is faster than a turtle."],
  videos=[("Comparative adjectives for kids", "apkbwRQkLv8")],
  quiz=[("An elephant is ___ than a mouse.", ["big", "bigger", "more big"], 1, "big → bigger."),
        ("A giraffe is ___ than a dog.", ["taller", "more tall", "tallest"], 0, "tall → taller."),
        ("A peacock is ___ than a crow.", ["beautifuler", "more beautiful", "beautiful"], 1, "Adjetivo largo → more beautiful."),
        ("A cheetah is ___ than a turtle.", ["fast", "faster", "more fast"], 1, "fast → faster.")]),
]

NAT = [
 dict(id="n-skeleton", s="nat", q=2, st="actual", p=1, t="The human skeleton",
  kid="Our skeleton helps us stand up straight and gives our body its shape. (El esqueleto nos sostiene y da forma.)",
  table={"head": ["Bone", "Hueso", "Where?"], "rows": [["skull", "cráneo", "head"], ["sternum", "esternón", "chest"], ["rib", "costilla", "chest"], ["vertebra", "vértebra", "back (spine)"], ["humerus", "húmero", "upper arm"], ["radius · ulna", "radio · cúbito", "forearm"], ["pelvis", "pelvis", "hips"], ["femur", "fémur", "thigh (muslo)"], ["patella", "rótula", "knee"], ["tibia · fibula", "tibia · peroné", "lower leg"]]},
  pts=["3 jobs: 1) protect organs, 2) give shape, 3) help us move", "Adults have 206 bones", "Ligaments join the bones",
       "Joints: where two bones meet (knees, elbows)", "Skull → protects the brain",
       "Rib cage → protects the lungs and the heart", "Pelvis → protects the bowels (intestines)"],
  listen=["The skull protects the brain.", "The rib cage protects the lungs and the heart.", "Adults have two hundred and six bones.", "The femur is in the thigh.", "The patella is in the knee."],
  videos=[("Bones and muscles – science for kids", "_LzxAp1y6rk")],
  quiz=[("How many bones does an adult have?", ["106", "206", "600"], 1, "206 bones."),
        ("The skull protects the…", ["brain", "heart", "stomach"], 0, "Skull (cráneo) → brain."),
        ("The rib cage protects the…", ["lungs and heart", "brain", "legs"], 0, "Rib cage (costillas) → lungs and heart."),
        ("Knees and elbows are…", ["joints", "muscles", "nerves"], 0, "Joints = articulaciones."),
        ("What joins the bones together?", ["ligaments", "blood", "skin"], 0, "Ligaments (ligamentos)."),
        ("The pelvis protects the…", ["bowels (intestines)", "brain", "eyes"], 0, "Pelvis → bowels."),
        ("The bone in your thigh (muslo) is the…", ["femur", "skull", "rib"], 0, "Femur = fémur, the longest bone."),
        ("The kneecap (rótula) is the…", ["patella", "pelvis", "sternum"], 0, "Patella = rótula."),
        ("The bone of the upper arm is the…", ["humerus", "tibia", "vertebra"], 0, "Humerus = húmero."),
        ("The backbone is made of small bones called…", ["vertebrae", "ribs", "teeth"], 0, "Vertebrae = vértebras."),
        ("True or false: The adult human body has 306 bones.", ["False", "True"], 0, "False: adults have 206 bones."),
        ("True or false: Joints are places where two bones meet.", ["True", "False"], 0, "True: joints (articulaciones)."),
        ("True or false: Our skeleton helps us stand up straight.", ["True", "False"], 0, "True.")]),
 dict(id="n-muscles", s="nat", q=2, st="actual", p=1, t="The muscles",
  kid="A muscle is a stretchy body part that tightens and relaxes to help you move.",
  pts=["More than 600 muscles in the body", "Muscles often work in pairs",
       "Bicep: front of the upper arm · Tricep: back of the upper arm", "3 types: skeletal, smooth, cardiac", "Cardiac muscle = the heart"],
  listen=["We have more than six hundred muscles.", "Muscles work in pairs.", "The heart is a cardiac muscle."],
  videos=[("Bones and muscles | Science for kids (Periwinkle)", "fbmD0Y8_OWE")],
  quiz=[("How many muscles do we have?", ["More than 600", "206", "Only 10"], 0, "More than 600 muscles."),
        ("The bicep is on the ___ of the upper arm.", ["front", "back"], 0, "Bicep = front."),
        ("The tricep is on the ___ of the upper arm.", ["front", "back"], 1, "Tricep = back."),
        ("The heart is a ___ muscle.", ["cardiac", "skeletal", "smooth"], 0, "Cardiac = del corazón."),
        ("Muscles often work in…", ["pairs", "circles", "bones"], 0, "In pairs: one pulls, the other relaxes.")]),
 dict(id="n-nervous", s="nat", q=2, st="actual", p=1, t="The nervous system",
  kid="The nervous system is the boss that controls everything your body does.",
  pts=["Nerves are made of cells called neurons", "Neurons send messages with tiny electrical signals",
       "Central Nervous System (CNS): brain + spinal cord", "Brain: thinks, feels and controls actions",
       "Spinal cord: a thick bundle of nerves down your back, like a highway",
       "Peripheral Nervous System (PNS): nerves to every part of the body"],
  listen=["The brain is the boss of the body.", "The spinal cord is like a highway.", "Nerves are made of neurons."],
  videos=[("The nervous system | Happy Learning", "483eonLwznc"), ("The nervous system | video for kids", "KZVeFTDszTs")],
  quiz=[("Nerves are made of cells called…", ["neurons", "bones", "muscles"], 0, "Neurons (neuronas)."),
        ("The CNS is the brain and the…", ["spinal cord", "heart", "stomach"], 0, "Brain + spinal cord."),
        ("Which part is the boss that thinks and feels?", ["brain", "tricep", "pelvis"], 0, "The brain."),
        ("Nerves that go to every part of the body are the…", ["PNS", "CNS", "rib cage"], 0, "Peripheral Nervous System."),
        ("The spinal cord is like a…", ["highway", "ball", "shell"], 0, "A highway of messages.")]),
 dict(id="n-digestion", s="nat", q=2, st="actual", p=1, t="Food's journey (digestion)",
  kid="The food travels: mouth → esophagus → stomach → small intestine → large intestine → rectum → anus.",
  pts=["Mouth: breaks the food into small pieces", "Esophagus: connects the mouth and the stomach",
       "Stomach: turns the food into a thick liquid", "Small intestine: absorbs the nutrients",
       "Large intestine: collects the waste to get rid of it", "The liver also helps digestion"],
  listen=["The mouth breaks the food into small pieces.", "The esophagus connects the mouth and the stomach.", "The small intestine absorbs the nutrients."],
  videos=[("The digestive system | Happy Learning", "v3E1txcKPe8"), ("Digestive system | Dr. Binocs", "ZBZWgrfZFbU")],
  quiz=[("Which part connects the mouth and the stomach?", ["esophagus", "liver", "rectum"], 0, "Esophagus (esófago)."),
        ("Which part absorbs the nutrients?", ["small intestine", "mouth", "large intestine"], 0, "Small intestine."),
        ("Which part breaks the food into small pieces?", ["mouth", "stomach", "anus"], 0, "The mouth (teeth)."),
        ("Which part turns the food into a thick liquid?", ["stomach", "esophagus", "mouth"], 0, "The stomach."),
        ("What comes after the stomach?", ["small intestine", "esophagus", "mouth"], 0, "Stomach → small intestine.")]),
 dict(id="n-plantparts", s="nat", q=1, st="repaso", p=2, t="Plants: parts and functions",
  kid="Each part of a plant has a job. (Cada parte de la planta tiene un trabajo.)",
  pts=["Roots: hold the plant and absorb water", "Stem: holds up the plant and carries water", "Leaves: make food for the plant with sunlight",
       "Flower: makes the seeds", "Fruit: protects the seeds", "Plants need water, sunlight, air and soil"],
  quiz=[("Which part absorbs water from the soil?", ["roots", "flower", "fruit"], 0, "Roots (raíces)."),
        ("Which part makes food with sunlight?", ["leaves", "roots", "stem"], 0, "Leaves (hojas)."),
        ("Which part protects the seeds?", ["fruit", "stem", "roots"], 0, "The fruit."),
        ("The stem…", ["carries water and holds up the plant", "makes seeds", "is under the soil"], 0, "Stem = tallo."),
        ("Plants need…", ["water, sunlight, air and soil", "only candy", "darkness"], 0, "Water, sunlight, air and soil.")]),
 dict(id="n-plantclass", s="nat", q=1, st="repaso", p=3, t="Plants: tree, bush, herb",
  kid="Plants are classified by their stem.",
  pts=["Tree: tall, one thick woody trunk", "Bush (shrub): woody stems, shorter than a tree", "Herb: soft green stem, small"],
  quiz=[("A plant with one thick woody trunk is a…", ["tree", "herb", "bush"], 0, "Tree (árbol)."),
        ("A small plant with a soft green stem is a…", ["herb", "tree", "bush"], 0, "Herb (hierba)."),
        ("A plant with many woody stems, shorter than a tree, is a…", ["bush", "herb", "tree"], 0, "Bush (arbusto).")]),
 dict(id="n-seeds", s="nat", q=1, st="repaso", p=2, t="Seeds and life cycle",
  kid="A seed has a baby plant inside. With water and warmth it germinates and grows.",
  pts=["Seed coat (testa): protects the seed", "Embryo: the baby plant", "Endosperm / cotyledon: food for the baby plant",
       "Monocot: 1 cotyledon (corn, rice) · Dicot: 2 cotyledons (bean)",
       "Angiosperms: seeds inside a fruit · Gymnosperms: seeds without fruit (pine cones)",
       "Life cycle: seed → germination → seedling → adult plant → flower → fruit"],
  quiz=[("The baby plant inside the seed is the…", ["embryo", "seed coat", "fruit"], 0, "Embryo (embrión)."),
        ("The seed coat…", ["protects the seed", "is the food", "is a root"], 0, "Testa = protección."),
        ("A bean has 2 cotyledons. It is a…", ["dicot", "monocot"], 0, "Di = 2."),
        ("Corn has 1 cotyledon. It is a…", ["monocot", "dicot"], 0, "Mono = 1."),
        ("What comes after germination?", ["seedling", "fruit", "seed"], 0, "Seed → germination → seedling.")]),
 dict(id="n-food", s="nat", q=1, st="repaso", p=3, t="Healthy food",
  kid="Healthy food gives you energy to learn and play. Eat fruits and vegetables every day.",
  pts=["Healthy: fruits, vegetables, water, milk, eggs, fish, rice", "Eat less: candy, soda, chips, fried food", "Drink water"],
  quiz=[("Which is healthy?", ["an apple", "a soda", "chips"], 0, "Fruit is healthy."),
        ("Which should we eat less?", ["candy", "vegetables", "water"], 0, "Too much sugar is not healthy."),
        ("The best drink is…", ["water", "soda", "energy drink"], 0, "Water.")]),
]

ENV = [
 dict(id="v-matter", s="env", q=1, st="repaso", p=2, t="States of matter",
  kid="Everything is made of matter. Matter can be solid, liquid or gas.",
  pts=["Solid: has its own shape (a ball, a rock, ice)", "Liquid: takes the shape of its container and flows (water, milk, juice)",
       "Gas: spreads out to fill the space (air, steam)"],
  listen=["Ice is a solid.", "Milk is a liquid.", "Air is a gas."],
  quiz=[("Ice is a…", ["solid", "liquid", "gas"], 0, "Ice has its own shape: solid."),
        ("Milk is a…", ["solid", "liquid", "gas"], 1, "It flows: liquid."),
        ("The air in a balloon is a…", ["solid", "liquid", "gas"], 2, "Air is a gas."),
        ("Which one takes the shape of its container?", ["liquid", "solid"], 0, "Liquids take the shape of the glass."),
        ("A basketball is a…", ["solid", "liquid", "gas"], 0, "The ball is solid (the air inside is gas).")]),
]
