# Matemática — contenido para el Centro de Estudios de Thiago
# Fuentes: resúmenes semanales y canal EVALUACIONES de 4°C_MATEMÁTICAS (Teams), libreta 1Q.
MAT = [
 dict(id="m-mult", s="mat", q=2, st="actual", p=1, t="La multiplicación y sus términos",
  kid="Multiplicar es sumar el mismo número varias veces, pero más rápido.",
  pts=["3 × 4 es sumar el 4 tres veces: 4 + 4 + 4 = 12",
       "Factores: los números que se multiplican (3 y 4)",
       "Factor que falta: 6 × ___ = 24 → ¿6 por cuánto da 24? → 4",
       "Producto: el resultado (12)",
       "El signo × se lee «por»",
       "El orden no cambia el producto: 3 × 4 = 4 × 3"],
  quiz=[("¿Cómo se escribe 5 + 5 + 5 como multiplicación?", ["3 × 5", "5 × 5", "3 + 5"], 0, "Sumas el 5 tres veces: 3 × 5 = 15."),
        ("En 6 × 7 = 42, ¿cómo se llama el 42?", ["Factor", "Producto", "Sumando"], 1, "El resultado de una multiplicación es el producto."),
        ("En 6 × 7 = 42, ¿qué son el 6 y el 7?", ["Factores", "Productos", "Restas"], 0, "Los números que se multiplican son los factores."),
        ("¿Qué suma es igual a 4 × 2?", ["2 + 2 + 2 + 2", "4 + 2", "2 + 4 + 4"], 0, "4 veces el 2: 2 + 2 + 2 + 2 = 8."),
        ("Hay 3 grupos de 5 manzanas. ¿Cuántas manzanas hay?", ["8", "15", "35"], 1, "3 × 5 = 15."),
        ("5 × ___ = 25", ["5", "4", "6"], 0, "5 × 5 = 25."),
        ("6 × ___ = 24", ["4", "3", "5"], 0, "6 × 4 = 24."),
        ("¿Qué multiplicación da 48?", ["8 × 6", "9 × 5", "7 × 7"], 0, "8 × 6 = 48."),
        ("4 macetas con 3 flores cada una. ¿Qué multiplicación es?", ["4 × 3 = 12", "4 + 3 = 7", "4 × 4 = 16"], 0, "4 grupos de 3: 4 × 3 = 12.")]),
 dict(id="m-propiedades", s="mat", q=2, st="actual", p=1, t="Propiedades de la multiplicación",
  kid="Las propiedades son trucos que siempre se cumplen y te ayudan a multiplicar más fácil.",
  pts=["Conmutativa: el orden no cambia el producto → 3 × 5 = 5 × 3 = 15",
       "Asociativa: puedes agrupar como quieras → (2 × 3) × 4 = 2 × (3 × 4) = 24",
       "Elemento neutro: todo número por 1 da el mismo número → 7 × 1 = 7",
       "Por cero: todo número por 0 da 0 → 9 × 0 = 0",
       "Revisa en el cuaderno el nombre exacto que usó la profe"],
  quiz=[("4 × 6 = 6 × ___", ["4", "6", "24"], 0, "Conmutativa: cambias el orden y da lo mismo."),
        ("8 × 1 = ?", ["8", "1", "9"], 0, "Por 1 queda igual: elemento neutro."),
        ("5 × 0 = ?", ["0", "5", "50"], 0, "Todo número por 0 da 0."),
        ("«3 × 5 = 5 × 3» es la propiedad…", ["conmutativa", "asociativa", "del cero"], 0, "Cambiar el orden = conmutativa."),
        ("(2 × 3) × 2 = ?", ["12", "7", "10"], 0, "2 × 3 = 6, y 6 × 2 = 12."),
        ("«(2 × 3) × 4 = 2 × (3 × 4)» es la propiedad…", ["asociativa", "conmutativa", "neutro"], 0, "Agrupar distinto = asociativa.")]),
 dict(id="m-monedas", s="mat", q=2, st="actual", p=1, t="Monedas y billetes (dólar)",
  kid="En Ecuador usamos el dólar. 1 dólar tiene 100 centavos.",
  pts=["Monedas: 1¢, 5¢, 10¢, 25¢, 50¢ y $1",
       "Billetes: $1, $5, $10, $20, $50 y $100",
       "4 monedas de 25¢ = $1",
       "2 monedas de 50¢ = $1",
       "10 monedas de 10¢ = $1"],
  quiz=[("¿Cuántos centavos tiene 1 dólar?", ["10", "100", "50"], 1, "1 dólar = 100 centavos."),
        ("¿Cuántas monedas de 25¢ forman 1 dólar?", ["2", "4", "5"], 1, "25 + 25 + 25 + 25 = 100 centavos."),
        ("¿Cuánto son 3 monedas de 10¢?", ["30¢", "13¢", "3¢"], 0, "3 × 10 = 30 centavos."),
        ("Tienes 2 monedas de 25¢ y 1 de 50¢. ¿Cuánto tienes?", ["$1", "75¢", "50¢"], 0, "25 + 25 + 50 = 100 centavos = $1."),
        ("Un helado cuesta 50¢. Compras 3. ¿Cuánto pagas?", ["$1,50", "$1,00", "53¢"], 0, "3 × 50 = 150 centavos = $1,50.")]),
 dict(id="m-probmult", s="mat", q=2, st="actual", p=1, t="Problemas con multiplicación",
  kid="Si la misma cantidad se repite, multiplica. Busca palabras como «cada», «veces» o «grupos de».",
  pts=["1. Lee el problema dos veces",
       "2. Subraya los números",
       "3. ¿Se repite la misma cantidad? → multiplica",
       "4. Escribe la operación",
       "5. Responde con número y palabra: «24 lápices»",
       "En la tarea: DATOS → OPERACIÓN → RESPUESTA"],
  quiz=[("Cada caja tiene 6 lápices. Hay 4 cajas. ¿Cuántos lápices hay?", ["10", "24", "20"], 1, "4 × 6 = 24 lápices."),
        ("Un carro tiene 4 ruedas. ¿Cuántas ruedas tienen 5 carros?", ["9", "20", "25"], 1, "5 × 4 = 20 ruedas."),
        ("Thiago encesta 3 canastas en cada partido. Juega 7 partidos. ¿Cuántas canastas?", ["21", "10", "24"], 0, "7 × 3 = 21 canastas."),
        ("«Hay 8 bolsas con 5 caramelos cada una.» ¿Qué operación usas?", ["8 + 5", "8 × 5", "8 − 5"], 1, "Se repite el 5 ocho veces: 8 × 5 = 40."),
        ("Una semana tiene 7 días. ¿Cuántos días tienen 3 semanas?", ["10", "21", "14"], 1, "3 × 7 = 21 días.")]),
 dict(id="m-reparto", s="mat", q=1, st="repaso", p=3, t="Reparto equitativo",
  kid="Repartir en partes iguales: todos reciben lo mismo y no sobra nada (o sobra poquito).",
  pts=["12 caramelos entre 3 niños → 4 para cada uno",
       "Comprueba multiplicando: 3 × 4 = 12"],
  quiz=[("10 galletas entre 2 niños. ¿Cuántas para cada uno?", ["5", "8", "12"], 0, "2 × 5 = 10."),
        ("15 lápices en 3 cajas iguales. ¿Cuántos en cada caja?", ["3", "5", "12"], 1, "3 × 5 = 15."),
        ("20 canicas entre 4 amigos. ¿Cuántas para cada uno?", ["5", "4", "16"], 0, "4 × 5 = 20."),
        ("¿Cómo compruebas que 18 entre 3 da 6?", ["3 × 6 = 18", "18 + 3 = 21", "18 − 6 = 12"], 0, "Multiplica: 3 × 6 = 18.")]),
 dict(id="m-numeros", s="mat", q=1, st="repaso", p=2, t="Números hasta 9 999",
  kid="Cada cifra vale según su lugar: unidades de mil (UM), centenas (C), decenas (D) y unidades (U).",
  pts=["5 372 = 5 UM + 3 C + 7 D + 2 U",
       "El 7 en 7 326 vale 7 000",
       "Para comparar, mira primero las UM, luego las C…",
       "< menor que, > mayor que"],
  quiz=[("5 UM + 3 C + 7 D + 2 U = ?", ["5 372", "5 237", "3 572"], 0, "Se escribe en orden: UM, C, D, U."),
        ("¿Cuánto vale el 7 en 7 326?", ["7", "700", "7 000"], 2, "Está en las unidades de mil."),
        ("¿Qué signo va?  5 234 __ 5 243", ["<", ">", "="], 0, "Iguales UM y C; en las D, 3 es menor que 4."),
        ("¿Cómo se escribe «cuatro mil cinco»?", ["4 500", "4 005", "4 050"], 1, "4 UM, 0 C, 0 D, 5 U."),
        ("¿Cuál es el número mayor?", ["8 099", "8 909", "8 990"], 2, "Todos tienen 8 UM; 8 990 tiene 9 C y 9 D.")]),
 dict(id="m-suma", s="mat", q=1, st="repaso", p=2, t="Suma con reagrupación y propiedades",
  kid="Si una columna suma más de 9, escribes las unidades y llevas 1 a la columna de la izquierda.",
  pts=["Suma de derecha a izquierda",
       "Conmutativa: el orden no cambia el resultado (15 + 28 = 28 + 15)",
       "Asociativa: agrupar distinto no cambia el resultado ((12 + 8) + 15 = 12 + (8 + 15))"],
  quiz=[("2 536 + 3 427 = ?", ["5 963", "5 953", "6 963"], 0, "6+7=13, llevas 1; 3+2+1=6; 5+4=9; 2+3=5."),
        ("15 + 28 = 28 + 15 es la propiedad…", ["Asociativa", "Conmutativa"], 1, "Cambia el orden: conmutativa."),
        ("(12 + 8) + 15 = 12 + (8 + 15) es la propiedad…", ["Asociativa", "Conmutativa"], 0, "Cambia cómo se agrupan: asociativa."),
        ("345 + 287 = ?", ["632", "622", "532"], 0, "5+7=12, llevas 1; 4+8+1=13, llevas 1; 3+2+1=6.")]),
 dict(id="m-resta", s="mat", q=1, st="repaso", p=1, t="Resta con reagrupación y su prueba",
  kid="Si la cifra de arriba es menor, pide prestado 1 a la cifra de la izquierda (ese 1 vale 10).",
  pts=["Minuendo − sustraendo = diferencia",
       "Resta de derecha a izquierda",
       "Prueba: diferencia + sustraendo = minuendo",
       "Ejemplo: 90 − 35 = 55 → prueba 55 + 35 = 90 ✔"],
  quiz=[("7 845 − 4 326 = ?", ["3 519", "3 529", "4 519"], 0, "5−6 no se puede: pides prestado → 15−6=9; 3−2=1; 8−3=5; 7−4=3."),
        ("¿Cuál es la prueba de 90 − 35 = 55?", ["55 + 35 = 90", "90 + 35 = 125", "55 − 35 = 20"], 0, "Diferencia + sustraendo = minuendo."),
        ("52 − 18 = ?", ["34", "44", "36"], 0, "12−8=4; 4−1=3 → 34."),
        ("En 80 − 25 = 55, ¿cuál es el minuendo?", ["80", "25", "55"], 0, "El minuendo es el número del que se resta."),
        ("1 000 − 356 = ?", ["644", "756", "654"], 0, "Prueba: 644 + 356 = 1 000.")]),
 dict(id="m-redondeo", s="mat", q=1, st="repaso", p=1, t="Redondeo",
  kid="Mira la cifra de la derecha. Si es 5 o más, subes. Si es 4 o menos, se queda igual.",
  pts=["5, 6, 7, 8, 9 → sube",
       "0, 1, 2, 3, 4 → se queda",
       "A la decena: 47 → 50; 43 → 40",
       "A la centena: 5 678 → 5 700",
       "A la unidad de mil: 3 456 → 3 000"],
  quiz=[("Redondea 47 a la decena", ["40", "50", "45"], 1, "La unidad es 7 (5 o más): sube a 50."),
        ("Redondea 5 678 a la centena", ["5 600", "5 700", "6 000"], 1, "La decena es 7: sube a 5 700."),
        ("Redondea 3 456 a la unidad de mil", ["3 000", "4 000", "3 500"], 0, "La centena es 4: se queda en 3 000."),
        ("Redondea 234 a la centena", ["200", "300", "230"], 0, "La decena es 3: se queda en 200."),
        ("Redondea 85 a la decena", ["80", "90", "85"], 1, "La unidad es 5: sube a 90.")]),
 dict(id="m-secuencias", s="mat", q=1, st="repaso", p=1, t="Secuencias aditivas",
  kid="En una secuencia aditiva siempre se suma el mismo número. Encuentra el salto y sigue.",
  pts=["10, 20, 30 → el salto es +10",
       "Resta dos números seguidos para encontrar el salto"],
  quiz=[("10, 20, 30, 40, __", ["45", "50", "60"], 1, "Salto de +10."),
        ("5, 10, 15, 20, __", ["25", "30", "21"], 0, "Salto de +5."),
        ("100, 200, 300, __", ["310", "400", "500"], 1, "Salto de +100."),
        ("3, 6, 9, 12, __", ["14", "15", "16"], 1, "Salto de +3 (¡es la tabla del 3!)."),
        ("¿Cuál es el salto en 25, 50, 75, 100?", ["5", "25", "50"], 1, "50 − 25 = 25.")]),
 dict(id="m-conversiones", s="mat", q=1, st="repaso", p=1, t="Medidas de longitud y conversiones",
  kid="Kilómetro (km) para distancias largas, metro (m) para cosas grandes, centímetro (cm) para cosas pequeñas.",
  pts=["1 km = 1 000 m",
       "1 m = 100 cm",
       "De grande a pequeño: multiplica (km → m → cm)",
       "De pequeño a grande: divide (cm → m → km)"],
  quiz=[("8 km = ? m", ["800", "8 000", "80"], 1, "8 × 1 000 = 8 000 m."),
        ("3 m = ? cm", ["30", "300", "3 000"], 1, "3 × 100 = 300 cm."),
        ("500 cm = ? m", ["5", "50", "500"], 0, "500 ÷ 100 = 5 m."),
        ("2 km = ? m", ["2 000", "200", "20 000"], 0, "2 × 1 000 = 2 000 m."),
        ("¿Qué unidad usas para medir un lápiz?", ["km", "m", "cm"], 2, "Es pequeño: centímetros.")]),
 dict(id="m-perimetro", s="mat", q=1, st="repaso", p=2, t="Perímetro",
  kid="El perímetro es la suma de todos los lados de una figura. Es el borde, como la línea de la cancha.",
  pts=["Suma todos los lados",
       "Cuadrado: lado × 4",
       "Rectángulo: largo + ancho + largo + ancho"],
  quiz=[("Triángulo con lados de 8 cm, 8 cm y 6 cm", ["22 cm", "20 cm", "24 cm"], 0, "8 + 8 + 6 = 22 cm."),
        ("Rectángulo de 9 cm de largo y 6 cm de ancho", ["15 cm", "30 cm", "54 cm"], 1, "9 + 6 + 9 + 6 = 30 cm."),
        ("Cuadrado de 7 cm de lado", ["28 cm", "14 cm", "49 cm"], 0, "7 × 4 = 28 cm."),
        ("El perímetro es…", ["lo de adentro de la figura", "la suma de sus lados", "el lado más largo"], 1, "Es el contorno: la suma de los lados.")]),
 dict(id="m-angulos", s="mat", q=1, st="repaso", p=2, t="Rectas y ángulos",
  kid="Las rectas se cruzan o no se cruzan. Donde se cruzan forman ángulos, que medimos con el graduador.",
  pts=["Paralelas: nunca se cortan (como los rieles del tren)",
       "Perpendiculares: se cortan formando un ángulo recto (90°)",
       "Segmento: tiene principio y fin",
       "Semirrecta: tiene principio y no tiene fin",
       "Agudo: menos de 90° · Recto: 90° · Obtuso: más de 90°"],
  quiz=[("Dos rectas que nunca se cortan son…", ["Perpendiculares", "Paralelas", "Segmentos"], 1, "Paralelas: siempre a la misma distancia."),
        ("Un ángulo de 90° es…", ["Agudo", "Recto", "Obtuso"], 1, "90° es el ángulo recto, como la esquina de un cuaderno."),
        ("Un ángulo de 45° es…", ["Agudo", "Recto", "Obtuso"], 0, "Menos de 90°: agudo."),
        ("Un ángulo de 120° es…", ["Agudo", "Recto", "Obtuso"], 2, "Más de 90°: obtuso."),
        ("¿Con qué instrumento se miden los ángulos?", ["Regla", "Graduador", "Compás"], 1, "El graduador (transportador).")]),
 dict(id="m-cuerpos", s="mat", q=1, st="repaso", p=1, t="Cuerpos geométricos",
  kid="Los cuerpos geométricos ocupan espacio: tienen caras, aristas y vértices.",
  pts=["Cara: la superficie plana",
       "Arista: donde se juntan dos caras",
       "Vértice: la esquina donde se juntan aristas",
       "Cubo: 6 caras, 12 aristas, 8 vértices",
       "Esfera: toda redonda (pelota de básquet)",
       "Cilindro: 2 bases circulares (lata)",
       "Cono: 1 base circular y un vértice (cono de helado)",
       "Pirámide: 1 base y caras triangulares"],
  quiz=[("Una pelota de básquet tiene forma de…", ["Cubo", "Esfera", "Cono"], 1, "Es toda redonda: esfera."),
        ("¿Cuántas caras tiene un cubo?", ["4", "6", "8"], 1, "Como un dado: 6 caras."),
        ("Una lata de atún tiene forma de…", ["Cilindro", "Pirámide", "Esfera"], 0, "Dos bases circulares: cilindro."),
        ("¿Cómo se llama la esquina donde se juntan las aristas?", ["Cara", "Vértice", "Base"], 1, "Vértice."),
        ("Un cono de helado tiene…", ["2 bases circulares", "1 base circular y un vértice", "6 caras"], 1, "El cono tiene una base circular y una punta.")]),
 dict(id="m-movimientos", s="mat", q=1, st="repaso", p=3, t="Movimientos en el plano",
  kid="Una figura se puede deslizar, girar o reflejar como en un espejo.",
  pts=["Traslación: se desliza sin girar",
       "Giro (rotación): da vueltas alrededor de un punto",
       "Simetría: como un espejo; las dos mitades son iguales"],
  quiz=[("Una figura que se desliza sin girar hace una…", ["Traslación", "Rotación", "Simetría"], 0, "Traslación = deslizar."),
        ("Las manecillas del reloj hacen un…", ["Giro", "Traslación", "Reflejo"], 0, "Giran alrededor del centro."),
        ("Una mariposa con dos alas iguales tiene…", ["Simetría", "Traslación", "Rotación"], 0, "Sus dos mitades son como un espejo."),
        ("¿Qué movimiento hace la puerta al abrirse?", ["Giro", "Traslación", "Simetría"], 0, "Gira sobre las bisagras.")]),
 dict(id="m-finanzas", s="mat", q=2, st="actual", p=2, t="Educación financiera",
  kid="El dinero se gana, se gasta y se ahorra. Ahorrar es guardar una parte para después.",
  pts=["Ahorro: guardar parte del dinero para una meta",
       "Cheque: papel para pagar con dinero de una cuenta del banco",
       "Tarjeta de crédito: el banco presta dinero y después hay que devolverlo",
       "Antes de comprar: ¿lo necesito o solo lo quiero?"],
  quiz=[("Ahorrar es…", ["gastar todo", "guardar una parte del dinero", "pedir prestado"], 1, "Ahorrar es guardar para después."),
        ("Con una tarjeta de crédito…", ["el dinero es gratis", "el banco presta y luego se paga", "no hay que pagar nunca"], 1, "Es un préstamo: se devuelve."),
        ("Un cheque sirve para…", ["pagar con dinero de una cuenta del banco", "jugar", "ahorrar monedas"], 0, "Es una orden de pago al banco."),
        ("Quieres unas zapatillas de $40 y ahorras $10 por mes. ¿En cuántos meses las compras?", ["2", "4", "10"], 1, "4 × 10 = 40.")]),
]
